version: 2.1

orbs:
  sentry-cli-docker: rochet2/sentry-cli-docker@volatile

executors:
  my-executor:
    working_directory: ~/app
    machine:
      image: ubuntu-1604:201903-01

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: run cypress tests
          command: |
            docker build -t foo .
            docker run -d foo
            sleep 1
      - sentry-cli-docker/greet:

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
